dotnet/dotnet

src/vstest/src/package/licenses/LICENSE_NET.txt, src/vstest/src/package/licenses/LICENSE_VS.txt
This reverts commit 11f290176e4d51aa7fb81bb1d6b4ec90df26fef2 from 11f290176e4d51aa7fb81bb1d6b4ec90df26fef2.
Removing the exclusion in https://github.com/dotnet/installer/pull/17033 is not sufficient.
=> Revert "Remove cloaked licenses from vstest (#32)"

README.md
The wording is incorrect as it was coupled to the .NET 9 release.  With the schedule changes this is now .NET 10.  I chose to not couple the wording here to a specific release, rather the completion of the project.  The Roadmap will also need updating.
=> Update VMR README.md timeframe around two-way code flow

repo-projects/Directory.Build.targets, repo-projects/runtime.proj
This avoids torn state when a repo uses an older Toolset compiler package.
Partially unblocks https://github.com/dotnet/dotnet/pull/233
=> Always use the .NET SDK compiler

repo-projects/wpf.proj
Contributes to https://github.com/dotnet/source-build/issues/3539 & https://github.com/dotnet/source-build/issues/3795
Got fixed with the latest source flow.
=> Remove warnAsError=false from wpf

src/runtime/eng/Publishing.props
In https://github.com/dotnet/dotnet/pull/278 I copied the logic from the SDK repo but in runtime we build the PGO bits as *NonShipping*. This fixes that mistake.
=> Fix mistake in PGO runtime publishing

.devcontainer/init-toolset.sh
Otherwise the Codespaces creation fails
=> Fix .devcontainer init-toolset.sh to actually install the dotnet sdk

src/runtime/eng/Signing.props
Signing with hardening for a few mac binaries appears to cause failures. Need to understand this better but for now, only sign those items would normally be signed in staging.
=> [release/10.0.1xx-preview4] Remove real-signing from a few mac binaries

eng/pipelines/templates/stages/source-build-and-validate.yml
The source-only jobs are failing in the UB pipeline because they are attempting to test in the same job as the build occurs. Testing is supposed to be disabled in those jobs as it happens later in a separate stage. Fixed the logic to correctly set this state.
=> Fix source-only jobs to not test in UB

eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/SigningValidation.cs
Related to https://github.com/dotnet/source-build/issues/5117
The VMR validation is currently green despite no files being processed, which is confusing from a UX perspective because it looks like the validation was successful. To fix this, we should log an error when no files are processed.
=> VMR signing validation should fail when no files are processed

eng/pipelines/templates/steps/vmr-validate-installers.yml, repo-projects/scenario-tests.proj, test/Microsoft.DotNet.Installer.Tests/Microsoft.DotNet.Installer.Tests.csproj, test/Microsoft.DotNet.Installer.Tests/installer-tests-prereqs.proj
Fixes: https://github.com/dotnet/source-build/issues/5053
Installer tests require scenario-tests package, which is not published anymore from any vertical.
This PR modifies installer tests project to build scenario-tests repo, as a dependency (project reference). Building scenario-tests, like any other repo in VMR, requires that UnifiedBuild.Tasks assembly is built first. That project is now also built as a required dependency of installer tests project.
- Separate traversal project was needed for build ordering of the dependencies.
- We don't want and don't need to build dependencies for scenario-tests project (repo), it builds OK without them. This required a new property, `SkipScenarioTestsDependencies`, to skip the build of project's references/dependencies.
- When skipping …
=> Build scenario-tests in installers validation job

repo-projects/Directory.Build.targets, src/arcade/eng/common/core-templates/steps/source-build.yml
The SB repo template shouldn't publish as it doesn't produce the intermediate package anymore.
... and copy eng/common files from arcade instead of VMR orchestrator. That one is the source when flowing eng/common to external repos, not the VMR orchestrator ones.
Unblocks https://github.com/dotnet/source-build-externals/pull/477
=> Remove publish arg from SB repo template

Directory.Build.props, eng/pipelines/templates/stages/vmr-verticals.yml, repo-projects/runtime.proj, src/runtime/eng/DotNetBuild.props
Extracted from https://github.com/dotnet/dotnet/pull/176
Avoid the indirection and just use the properties directly that runtime expects without the `DotNetBuild` prefix.
=> Consolidate runtime mono feature properties

Directory.Build.props, eng/init-poison.proj, eng/pipelines/templates/jobs/vmr-build.yml, repo-projects/Directory.Build.props, repo-projects/Directory.Build.targets
Extracted from https://github.com/dotnet/dotnet/pull/176
Put the poison result files under `artifacts\log\<config>\`  and avoid the now unnecessary copy step in the YML.
Also remove the unnecessary `PrebuiltReportsToMove` Move operation as the files already get written to the VMR log directory.
This makes everything nicely contained under the log directory (prebuilt + poison + sbrpusage + repo logs)
=> Put poison results under ArtifactsLogDir

src/runtime/eng/Publishing.props
Re-apply https://github.com/dotnet/dotnet/commit/8988fc0dbd882cb707f5397b7c7eb6174e56638b again as the runtime flow is currently blocked.
=> Fix pgo publishing (again)

eng/pipelines/templates/jobs/sdk-diff-tests.yml, eng/tools/CreateBaselineUpdatePR/PRCreator.cs
Closes https://github.com/dotnet/source-build/issues/5118
Switching to the dotnet/dotnet repo in [dotnet/dotnet#331](https://github.com/dotnet/dotnet/pull/331) caused the PR baseline update tool to incorrectly delete files when creating PRs. This happened because the the github API can only recursively fetch up to 100,000 files from a tree, and due to the size of the dotnet/dotnet repository, the entire test/ directory was excluded. As a result, the PR baseline update tool mistakenly identified the files as deleted when, in fact, they were not fetched.
This PR resolves the issue by ensuring that only a subset of files in the desired path are fetched from the original tree.
[Test pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2702494&view=results)
=> Fix `CreateBaselineUpdatePR` tool deleting files

repo-projects/roslyn.proj
roslyn has a live subscription on command-line-api and therefore we should have a repo dependency in the VMR
```
https://github.com/dotnet/command-line-api (.NET Libraries) ==> 'https://github.com/dotnet/roslyn' ('main')
- Id: 865c4ec8-62fa-4945-9bea-08d947dddb07
- Update Frequency: EveryDay
- Enabled: True
- Batchable: False
- PR Failure Notification tags:
- Source-enabled: False
- Merge Policies: []
- Last Build: 20250506.1 (493a1d270887d7c51372fd17f774ea44b0c3101a)
```
=> Add command-line-api dependency to roslyn.proj

eng/pipelines/ci.yml, eng/pipelines/templates/variables/vmr-build.yml
By default, msbuild and other repos do not enable IBC in main.
=> Only enable IBC in release branches

repo-projects/Directory.Build.targets, src/arcade/Documentation/UnifiedBuild/Unified-Build-Controls.md, src/arcade/eng/common/core-templates/steps/source-build.yml, src/arcade/src/Microsoft.DotNet.Arcade.Sdk/tools/RuntimeIdentifierInference.BeforeNETSdkTargets.targets, src/arcade/src/Microsoft.DotNet.Build.Tasks.Installers/build/installer.targets, src/aspnetcore/src/SiteExtensions/LoggingAggregate/src/Microsoft.AspNetCore.AzureAppServices.SiteExtension/Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj, src/roslyn/src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj, src/runtime/eng/pipelines/runtime.yml, src/runtime/eng/toolAot.targets, src/runtime/src/coreclr/runtime.proj, src/runtime/src/libraries/Microsoft.NETCore.Platforms/src/Microsoft.NETCore.Platforms.csproj
Remove `RuntimeOS` as we removed the last usage in the runtime repo a few weeks ago.
Rename `BaseOS` to `BaseRid` as various components in the stack have taken a dependency on the fact that `BaseOS` was a full RID and the name just caused confusion.
cc: @tmds @am11 @omajid
=> Clean up OS/RID controls used for Source-Build

eng/tools/BuildComparer/BuildComparer.cs
The asset and signing comparisons are failing because some repos no longer publish assets, which means that there's no merged manifests for those repos. We should skip throwing an error in the comparison when the merged manifests are not found for these repos.
[Test pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2704126&view=results)
=> Skip failing on repos that we know don't publish assets

eng/pipelines/templates/steps/vmr-validate-installers.yml
Fixes: https://github.com/dotnet/source-build/issues/5154
With PR https://github.com/dotnet/dotnet/pull/306 invocation of custom projects was updated to use `/p:Projects=<project>` instead of just passing the project as a cmd argument.
This requires that the project be specified with absolute path - originally this was a relative path.
=> Fix installer tests entry project path

eng/allowed-sb-binaries.txt, eng/allowed-vmr-binaries.txt
Fixes: https://github.com/dotnet/source-build/issues/5157
These files are already allowed in VMR.
=> Update allowed binaries files

src/arcade/src/Microsoft.DotNet.Arcade.Sdk/tools/Publish.proj, src/arcade/src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.props
We missed the signing glob in https://github.com/dotnet/arcade/pull/15678, so they haven't been getting signed.
Our SigningValidation jobs missed this because we don't currently validate signing for non-shipping assets.
Also, mark all of the "VS Redist" installer packages as DotNetReleaseShipping to get the right validation run on them.
=> Fix signing globs for cross-arch MSIs

eng/PublishSourceBuild.props, eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/UpdateNuGetConfigPackageSourcesMappings.cs, test/Microsoft.DotNet.SourceBuild.Tests/assets/PoisonTests/PoisonUsage.txt, test/Microsoft.DotNet.Tests/PackageSourceMappingsTests.cs
There are two sources that contain `NETStandard.Library` targeting pack packages - `previously-source-built` and `reference`. Due to non-determinism in NuGet restore, package could be resolved from either location. Anything coming from PSB has poisons marked as `AssemblyAttribute` type. Anything coming from live poisoned build of SBRP repo will use `SourceBuildReferenceAssembly` type.
In `previously-source-built` source, SBRP packages are located in a subfolder: `SourceBuildReferencePackages`
We plan to remove SBRP packages from PSB archive - the work is tracked in https://github.com/dotnet/source-build/issues/4930
There are 3 changes in this PR:
- Stop adding package source mappings for packages under `previously-source-built/SourceBuildReferencePackages` by enumerating only top …
=> Fix intermittent poison test failures

eng/Publishing.props, eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/ReadRepoInfoFromSourceManifest.cs, repo-projects/Directory.Build.targets
Adds RepoOriginalSourceRevisionId to the repo build parameters which is the commit sha from the source-manifest.json, i.e. the last merged forward flow commit of the repository.
Fixes https://github.com/dotnet/source-build/issues/5155
=> Pass repository last flow sha to the repo build

test/Microsoft.DotNet.SourceBuild.Tests/BaselineHelper.cs
Fixes: https://github.com/dotnet/source-build/issues/5141
Updated all instances of `Assert.Null(message);` with `Assert.True(message == null, message);`
Verified locally. Here's the produced output for a sample injected failure in poison tests:
Before:
```
Error Message:
Assert.Null() Failure: Value is not null
Expected: null
Actual:   "\nExpected file '/src/git/dotnet3/artifacts/bin/Mi"···
```
After:
```
Error Message:
Expected file '/src/git/dotnet3/artifacts/bin/Microsoft.DotNet.SourceBuild.Tests/Release/assets/PoisonTests/PoisonUsage.txt' does not match actual file '/src/git/dotnet3/artifacts/TestResults/Release/UpdatedPoisonUsage.txt`.
diff --git a/src/git/dotnet3/artifacts/bin/Microsoft.DotNet.SourceBuild.Tests/Release/assets/PoisonTests/PoisonUsage.txt …
```
=> Fix error message truncation

eng/pipelines/templates/jobs/vmr-build.yml
Resolves https://github.com/dotnet/source-build/issues/5181 Sometimes the pre-publish path doesn't exist
=> Continue on error when publishing artifacts on failure

repo-projects/Directory.Build.targets
Otherwise SBRP builds with bootstrap Arcade but with _a_ version of eng/common (the one that got last synced) which makes it really hard to make changes to eng/common in the VMR.
=> Fix UpdateEngCommonFiles target not applying to SBRP

eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/UpdateNuGetConfigPackageSourcesMappings.cs
Prompted by https://github.com/dotnet/dotnet/pull/550
Fixed all three instances of use of `Descendents()` method where `Elements()` is more correct.
=> Improve resilience with malformed NuGet.config files

src/arcade/global.json, src/arcade/src/Microsoft.DotNet.Helix/Sdk/tools/dotnet-cli/DotNetCli.props
... bring it in sync with the bootstrap SDK version. Contributes to https://github.com/dotnet/source-build/issues/5189
=> Update outgoing src/arcade/global.json sdk version

eng/common/build.sh
Fixes https://github.com/dotnet/source-build/issues/5191
This originally got fixed in https://github.com/dotnet/arcade/commit/d7540e540636883d3d080d087223d28b6b7395ae and is already part of the VMR non-bootstrap (live) eng/common layout.
But until we re-bootstrap to a newer Arcade that brings the updated eng/common files with the fix, manually backport this to the bootstrap layout.
=> Fix productbuild switch in bootstrap eng/common layout

eng/pipelines/templates/jobs/vmr-build.yml, eng/pipelines/templates/stages/vmr-build-with-join.yml
Contributes to: https://github.com/dotnet/arcade-services/issues/4539
Small update in template name as discussed in https://github.com/dotnet/arcade/pull/15840#discussion_r2093238054
=> Rename vmr-sync template reference

src/nuget-client/eng/dotnet-build/build.sh
These two are flags and don't need double shift.
Was trying https://github.com/dotnet/source-build/issues/5135#issuecomment-2887537250 and ran into
```sh
$ ./build.sh --clean-while-building --prep -sb --os linux --arch riscv64 -p:OfficialBuildId=$(date +%Y%m%d).1
...
DirSize Before Building nuget-client
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        72G   39G   34G  54% /dotnet
/dotnet/repo-projects/Directory.Build.targets(517,5): error MSB3073: The command "/dotnet/src/nuget-client/eng/dotnet-build/build.sh   --sourceBuild --configuration Release --verbosity minimal /p:TargetRid=linux-riscv64 /p:OfficialBuildId=20250516.101 /p:DotNetPackageVersionPropsPath=/dotnet/artifacts/obj/PackageVersions/PackageVersions.nuget-client.props …
```
=> Fix double shift args in nuget-client

eng/init-detect-binaries.proj
For whatever reason, binary detection runs really slow in my dev container (7 minutes). I see it runs quickly in the pipelines though. But I'd like a way to skip it.
=> Provide a way to skip binary detection

eng/allowed-sb-binaries.txt, eng/allowed-vmr-binaries.txt
Working around dotnet/arcade#15731
Fixes https://github.com/dotnet/dotnet/issues/650
=> Update allowed-sb-binaries.txt to exclude MicroBuild

eng/tools/BuildComparer/BuildComparer.cs
Related to https://github.com/dotnet/source-build/issues/5137
We are turning on `isAssetlessBuild` in VMR repos that don't need to retain their official build. As a result, VMR comparison is failing for these repos, so these repos need to be excluded from the VMR comparison.
This PR adds runtime to the exclusion list.
=> Exclude runtime from VMR comparison

eng/pipelines/templates/variables/vmr-build.yml
We don't actually need the XL pool for this, and the XL pool only has a few machines.
=> Use non-XL pool for tall stacks

repo-projects/Directory.Build.props, src/arcade/eng/common/build.sh, src/fsharp/build.sh, src/fsharp/eng/build.sh, src/nuget-client/eng/dotnet-build/build.sh, src/roslyn/build.sh, src/roslyn/eng/build.sh, src/runtime/build.sh, src/runtime/eng/build.sh
Currently, running the following command fails:
$ ./build.sh --prep --source-build /p:OfficialBuilder='Red Hat'
Lots of scripts and projects assume that there are no spaces in OfficialBuilder (and other properties). Having spaces breaks in all sorts of places. This is a minimal fix to try and resolve that.
The primary change is to use bash arrays to store values (properties and arguments) to make sure they are quoted correctly when passed to other places.
=> Support having spaces in OfficialBuilder

src/sdk/src/Layout/redist/targets/GenerateInstallerLayout.targets
Fixes internal issue reported where the .NET 10.0.100 Preview 4 SDK didn't have R2Rd Roslyn in the Exe/Msi installers.
Main PR at https://github.com/dotnet/sdk/pull/49096
=> [release/10.0.1xx-preview5] Copy files for MSI layout from the post-crossgen'd location

src/aspnetcore/Directory.Build.props, src/aspnetcore/eng/Signing.props
Follow-up to https://github.com/dotnet/aspnetcore/pull/62048. `Sign.proj` doesn't import D.B.P, but it does import eng/signing.props.
=> [preview5] Move SIGN NoWarn to Signing.props

src/arcade/global.json
The .NET SDK version got incorrectly downgraded in yesterday's arcade -> forward flow PR: https://github.com/dotnet/dotnet/commit/f2198a60a6a84945ffcffb6cf319e937b44fa0a0#r157738288
=> Revert global.json SDK change

src/nuget-client/eng/dotnet-build/build.ps1, src/nuget-client/eng/dotnet-build/build.sh
- Add warnAsError, nodereuse argss
- Add ci arg to the Unix script
- Only create a binlog on Unix when the -bl switch is passed in
- Use the same dotnet msbuild invocation as in arcade eng/common scripts
=> Add missing CLI args to nuget-client VMR scripts

src/arcade/eng/common/build.sh, src/fsharp/eng/build.sh, src/nuget-client/eng/dotnet-build/build.sh, src/roslyn/eng/build.sh, src/runtime/eng/build.sh
Fix broken builds on macOS. macOS ships with an older version of bash, which doesn't expand empty arrays correctly. So check that arrays are not empty before expanding them.
=> Fix bash array expansion on macOS

eng/vmr-msft-comparison-baseline.json
Part of https://github.com/dotnet/source-build/issues/5196. Command-line-api isn't built out of the VMR, and we have a new non-shipping SDK package.
=> Baseline 2 more missing assets

eng/pipelines/templates/stages/vmr-validation.yml, eng/pipelines/templates/steps/vmr-validate-installers.yml
Fixes: https://github.com/dotnet/dotnet/issues/707
[Verification build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2720053&view=artifacts&pathAsName=false&type=publishedArtifacts)
=> Publish build logs for installer tests jobs

src/arcade/global.json
Mistake from https://github.com/dotnet/dotnet/pull/933
=> Fix dotnet version in arcade global.json

repo-projects/Directory.Build.props, repo-projects/Directory.Build.targets
Continuation of https://github.com/dotnet/dotnet/commit/1801a223d0cc621cb94e43a272014985bee87113
This improves scheduling the inner repos and with that reduces the overall build time by getting runtime (which is on the hot path) to start to build earlier. Additionally, this makes the VMR build more aligned with the rest of the product by using P2Ps to build dependencies.
---
NuGet is responsible for calculating transitive project references in general. A project's project.assets.json file contains a node for the transitive p2ps. At build time a target then runs that reads that information and adds the transitive p2ps to an item group so that transitives are also getting built as part of the `ResolveProjectReferences` target. That's how the product works.
In the VMR we weren't defining P2P …
=> Build RepositoryReferences as P2Ps and use NuGet's transitive P2P calculation

repo-projects/scenario-tests.proj
Noticed in https://dev.azure.com/dnceng/internal/_build/results?buildId=2727981&view=logs&j=6e593626-f6df-5699-84b9-2127a964bf7b&t=1790d872-a33d-57ac-2a4d-ca6c60215859
This one fixes task projects getting built twice because the `SkipScenarioTestsDependencies` global property was flowing to them.
=> Fix overbuilding task projects when SkipScenarioTestsDependencies=true

eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/SigningValidation.cs
Fixes signing validation not finding any files to sign: https://dev.azure.com/dnceng/internal/_build/results?buildId=2729581&view=logs&j=2e220694-fd2b-5e09-0c04-ea9444ccf11c&t=aff2499f-2ea2-5f35-dcec-09ac00ac494f
=> Search subdirectories for manifest files

eng/pipelines/templates/stages/vmr-verticals.yml, repo-projects/arcade.proj
This will allow the cross-OS DAC join job to start while some of the buildpass1 windows verticals are running, reducing the load on the pool when the rest of the buildpass2 jobs can start.
Internal PR: https://dev.azure.com/dnceng/internal/_build/results?buildId=2729119&view=results
=> Remove dependency from Cross-OS DAC join job on the Windows verticals.

repo-projects/scenario-tests.proj
The ValidateInstallers jobs need to build scenario-tests in isolation without any of its dependencies. Due to P2Ps and their transitive nature when using NuGet, they were still flowing into
Microsoft.DotNet.Installers.Tests.csproj as transitive P2Ps.
Use PrivateAssets="all" in scenario-tests.proj to make them non-transitive.
=> Fix scenario-tests invocation in ValidateInstallers jobs

eng/RuntimeIdentifier.props, repo-projects/runtime.proj, src/diagnostics/Directory.Build.props, src/diagnostics/eng/Build-Native.cmd, src/diagnostics/eng/build.sh, src/diagnostics/eng/native/build-commons.sh, src/sdk/src/Layout/redist/targets/GenerateBundledVersions.targets
Cleans up usages of OutputRid that weren't covered in https://github.com/dotnet/runtime/pull/116259.
@ViktorHofer ptal.
=> Clean up remaining OutputRid usages.

eng/pipelines/templates/stages/source-build-and-validate.yml, eng/pipelines/templates/stages/vmr-build.yml, eng/pipelines/templates/stages/vmr-verticals.yml
Follow up to https://github.com/dotnet/dotnet/pull/1189
This PR fixes two issues with running repo-level VMR verification pipelines in CI mode.
Fixes:
- `VMR_SourceOnly_Validation` stage can only run if built from VMR as it depends on two unified-build stages
- Adds a condition for a verification that only runs in CI mode - `unified-build-windows-buildtests`
=> Allow VMR verification pipelines to run in CI mode

test/Microsoft.DotNet.Tests/PackageSourceMappingsTests.cs, test/Microsoft.DotNet.UnifiedBuild.Tests/NugetPackageContentTests.cs
File.OpenWrite will open an existing file which means if you write data that is shorter than the existing data the file will be corrupt. This is documented on https://learn.microsoft.com/en-us/dotnet/api/system.io.file.openwrite
> The OpenWrite method opens a file if one already exists for the file path, or creates a new file if one does not exist. For an existing file, it does not append the new text to the existing text. Instead, it overwrites the existing characters with the new characters. If you overwrite a longer string (such as "This is a test of the OpenWrite method") with a shorter string (such as "Second run"), the file will contain a mix of the strings ("Second runtest of the OpenWrite method").
Use File.Create instead in cases where we want to actually create or write into a …
=> [tests] Don't use File.OpenWrite when trying to overwrite a file

src/sdk/eng/Versions.props, src/templating/eng/Versions.props
Related to https://github.com/dotnet/dotnet/issues/1106
Updates to 2xx branding. Based off of https://github.com/dotnet/sdk/commit/038ac58fa1 and https://github.com/dotnet/templating/commit/4503bd8728053b06932cd2c45f918dbf1a914b30
=> Initial branding for 2xx

eng/update-band.ps1, eng/update-band.sh
This PR includes some updates to the bash and powershell scripts to handle merge conflicts in repos that _are_ included in the non-1xx branches.
=> Require user interaction when merge conflicts are encountered

eng/pipelines/templates/stages/vmr-build.yml
Publishing now pushes out the source-built assets. Add the missing stage dependency
=> Add a dependency on the source-build build for publishing

src/aspnetcore/src/Framework/App.Runtime/src/Microsoft.AspNetCore.App.Runtime.Composite.sfxproj, src/aspnetcore/src/Framework/App.Runtime/src/Microsoft.AspNetCore.App.Runtime.sfxproj
I recently made a change in aspnetcore to explicitly include the native .pdb in aspnetcore's SharedFx: https://github.com/dotnet/aspnetcore/pull/62124. However, that change didn't work in the VMR since `BuildNative` is set to `true` in the vertical that builds the SharedFx. We should always include that .pdb, not just when `BuildNative` is false.
=> Always include native .pdb in aspnetcore SharedFx

src/runtime/eng/Subsets.props
It's failing on the official build, so punt on packaging for now.
=> Punt on cdac transport pack for linux-musl

eng/PublishSourceBuild.props, eng/VmrLayout.props, eng/finish-source-only.proj
Contributes to #1465
For building the VMR from a 2xx branch, we won't be building the repos of the shared component repos like runtime and aspnetcore. That means we don't have access to the symbols that would have been produced from these builds in order to include in the `dotnet-symbols-all` tarball produced by a source-only build. These PDBs are necessary to include in that tarball.
In order to get these PDBs included, we first need to have access to the PDBs that were produced from the build that produced the shared components. This updates the build so that the `dotnet-symbols-all` tarball is added to the source build artifacts tarball. This will provide a 2xx build with access to these PDBs since it will consume the artifacts tarball as input.
=> Include symbols in SB artifacts

repo-projects/sdk.proj, src/sdk/eng/Versions.props, src/sdk/src/Workloads/VSInsertion/workloads.csproj
Fixes https://github.com/dotnet/source-build/issues/5298
Allows source-build to override the Emscripten package version. Since all package versions are based off the `OfficialBuildId`, we know that the Emscripten packages will match the package versions of the runtime which are correctly lifted in the `sdk` repo. So I've chosen STJ as the one to match since that is likely to always exist as a dependency of the repo.
=> Sync emscripten workload version with common runtime version

eng/pipelines/templates/jobs/vmr-build.yml
Helps with https://github.com/dotnet/dotnet/issues/1072
Keep osx still disabled as it doesn't have enough disk space. Validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2760626&view=results
=> Keep intermediates on Linux (internal)

src/aspnetcore/eng/targets/CSharp.Common.targets
This should reenable us to have repo specific commit diffs for benchmarking regression/improvement analysis.
Will probably want to do the same in dotnet/runtime assuming this works.
Question: Do we only want to do this for nightlies? Should it be disabled for official builds?
Edit: Maybe we want `OriginalRepoCommitUrl` as well?
e.g. Today we have:
```
[assembly: AssemblyMetadata("CommitHash", "67889d9d2f21a890ac29bcd175c0d1937a401781")]
[assembly: AssemblyMetadata("SourceCommitUrl", "https://github.com/dotnet/dotnet/tree/67889d9d2f21a890ac29bcd175c0d1937a401781")]
```
=> Use RepoOriginalSourceRevisionId in ASP.NET Core

repo-projects/runtime.proj
Should unblock main official builds
=> Build all runtime packs even in PgoInstrument builds

src/aspnetcore/eng/targets/Wix.Common.targets
Issue in Preview 7 where a couple non-shipping VS redist packages were getting 10.0.0-preview.N versions.
=> Fix stable versioning

src/sdk/src/Layout/redist/redist.csproj
Fixes the official build BP3 windows legs by making sure that the bundle.wixproj gets restored.
=> Restore bundle.wixproj in BP3

src/sdk/src/Layout/pkg/windows/bundles/sdk/bundle.wixproj
WiX 5 supports native bundles, but we need to retain them as 32-bit. Since the `InstallerPlatform` is always `x86` for bundles, this causes the SDK to always default `DOTNETHOME` to `ProgramFilesFolder` by selecting `DOTNETHOME_X86. It should instead set the variable name based off the `TargetArchitecture`.
Manual testing on Sandbox to verify that it now sets the correct directory value. 
Before:
```
[66758:60EA0][2025-08-05T13:12:01]i001: Burn x86 v5.0.2+131262537fc56e24f4ff1afaf35094dc81e2132d, Windows v10.0 x64 (Build 26100: Service Pack 0), path: C:\Users\*****\Downloads\dotnet-sdk-10.0.100-rc.1.25405.103-win-x64.exe
[66758:60EA0][2025-08-05T13:12:01]i000: Initializing formatted variable 'DOTNETHOME' to value '[DOTNETHOME_X86]'
```
After:
```
[191C:1480][2025-08-05T14:26:54]i001: Burn …
```
=> Fix PlatformToken value for SDK bundle

eng/pipelines/source-build-sdk-diff-tests-unofficial.yml, eng/pipelines/vmr-license-scan-unofficial.yml
Contributes to https://github.com/dotnet/source-build/issues/5290
This is a follow-up to https://github.com/dotnet/dotnet/pull/1745 New pipeline YMLs were created without `sdl` parameter. This caused the pipeline validation failure.
It works fine now - pipeline runs:
https://dev.azure.com/dnceng/internal/_build/results?buildId=2766507&view=results
https://dev.azure.com/dnceng/internal/_build/results?buildId=2766511&view=results
=> Add the missing sdl parameter to new unofficial pipelines

src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.csproj
An attempt to unblock https://github.com/dotnet/sdk/pull/50073. 
For simplicity, I'm just fixing up pack but not stopping the ilmerge. I'll do that in a follow-up PR on the NuGet side that has tests. 
This is just the faster way to flow the changes.
=> Stop packing ilmerged pack

src/arcade/Directory.Packages.props, src/arcade/eng/Version.Details.props, src/arcade/eng/Version.Details.xml
These are no longer required now that the source-build external are included in SBRP which builds before arcade.  It is best to not declare external package dependencies in V.D.xml because it can introduce differences between repo and VMR builds.
=> Remove arcade Version.Details.xml entries for external packages

eng/pipelines/official.yml
Update the binskim scan paths to a pattern similar to sdk's. Hits binaries properly, rather than relying on artifact upload.
=> Update binskim scan paths to hit artifact dirs

test/Microsoft.DotNet.Installer.Tests/Config.cs, test/Microsoft.DotNet.Installer.Tests/LinuxInstallerTests.cs, test/Microsoft.DotNet.Installer.Tests/Microsoft.DotNet.Installer.Tests.csproj
Contributes to https://github.com/dotnet/dotnet/issues/1011
The package installer tests in the VMR pipeline require the ability to install the `dotnet-sdk` deb/rpm packages. But these packages are dependent on the runtime packages (e.g. `dotnet-runtime`) which are not produced in a non-1xx branch of the VMR.
To solve this, these dependent packages are downloaded from ci.dot.net where they've been published by Arcade for each VMR build. The version of the 1xx build is determined by the VMR's configuration where it has a `MicrosoftNETSdkVersion` property that indicates this dependency. The condition for knowing whether this is in the context of a 1xx branch or not is determined by the `DotNetBuildSharedComponents` property which is `true` only in the context of a 1xx branch.
=> Package installer test support for non-1xx branches

eng/pipelines/templates/jobs/vmr-build.yml, eng/pipelines/templates/steps/vmr-validate-installers.yml, eng/pipelines/templates/steps/vmr-validate-signing.yml
We don't use these iOS/tvOS simulators in the VMR build and they take up a significant amount of disk space.
Available disk space increased from 44GB to 160GB and allows us to turn off clean-while-building for macOS jobs as well.
=> Free up disk space by deleting simulator runtimes on macOS

repo-projects/Directory.Build.targets, repo-projects/runtime.proj, src/runtime/eng/build.ps1, src/runtime/eng/build.sh
This will ensure that all outputs from the .NET runtime build will always be built based on the same commit (the commit that's building), ensuring that if/when we fix a CVE, all of our components in the .NET 10 build ship with the fix (nothing in the runtime repo that ships NativeAOT'd uses the N-1 build).
=> [release/10.0.1xx] Enable runtime's bootstrap build in all VMR builds

eng/pipelines/templates/jobs/vmr-build.yml, eng/pipelines/templates/steps/vmr-validate-installers.yml, eng/pipelines/templates/steps/vmr-validate-signing.yml
Backport of https://github.com/dotnet/dotnet/pull/2013 and https://github.com/dotnet/dotnet/pull/2038
=> Free up disk space by deleting simulator runtimes on Apple jobs

eng/tools/ChangeValidation/ExclusionFileValidation.cs
This didn't show in https://github.com/dotnet/dotnet/pull/2095 because we don't run this job in Maestro PRs.
Causes this: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1131345&view=logs&j=912e8062-b0ba-5930-681b-db020daf9df9&t=9a5472b0-d287-5f30-37b7-302b6e277fb9&l=12
=> Fix a usage of a changed DarcLib API

repo-projects/runtime.proj
Fixes a regression in the official build
=> [10.0.1xx] Disable bootstrap on BuildPass >=2 builds

eng/pipelines/templates/jobs/vmr-build.yml
Fixes: https://github.com/dotnet/source-build/issues/5294
This PR changes the step sequence to execute code after updating owner permissions, addressing the permission denied issue.
=> Move code execution after owner permission update

src/sdk/eng/Versions.props
The RC2 happened in the orange commit and the next backflow didn't have the change because we were still in the process of rolling out the version file synchronization:
=> Update SDK branding from RC1 to RC2

src/sdk/src/Layout/redist/targets/GenerateBundledVersions.targets, src/sdk/src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs
Try using the non-portable cg2/ilc when targeting any non-portable RID, not just the non-portable RID matching the SDK RID.
Fixes dotnet/source-build#5225
=> Adjust non-portable RID handling for tool packs to handle cross builds between non-portable RIDs

src/sdk/src/Layout/pkg/dotnet-sdk.proj
Cherry pick of https://github.com/dotnet/dotnet/commit/544d4310bec510b8472a773ea3ceb74af499dc7d which got reverted amidst the SDK codeflow misconfiguration
=> Remove FPM tooling support from SDK

src/sdk/src/Layout/pkg/dotnet-sdk.proj
Cherry pick of https://github.com/dotnet/dotnet/commit/544d4310bec510b8472a773ea3ceb74af499dc7d which got reverted amidst the SDK codeflow misconfiguration
=> [release/10.0.1xx] Remove FPM tooling support from SDK

src/sdk/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets, src/sdk/test/Microsoft.NET.Build.Tests/GivenThatWeWantToResolveConflicts.cs
it's causing perf regressions in orchardcore when TargetFrameworks is set to a single value. We believe this is because nuget and the project system aren't handling the default correctly in the project system cache and triggering multiple DTBs.
We found ~83k projects on nuget with a singular TargetFrameworks (279k with multiple values) out of 5M csproj files total.
=> Revert enabling package pruning for MT scenarios

eng/pipelines/templates/variables/vmr-build.yml
https://github.com/dotnet/runtime/issues/119174
=> Use macos-14-arm64 image in internal builds to workaround linker bug

eng/Publishing.props, eng/VmrLayout.props, eng/finish-source-only.proj, eng/pipelines/templates/jobs/vmr-build.yml, eng/pipelines/templates/stages/source-build-and-validate.yml, eng/pipelines/templates/stages/source-build-stages.yml, eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/CreateSourceArtifacts.cs, eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/Models/ArtifactType.cs, eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/Services/ProcessService.cs
Reverts https://github.com/dotnet/dotnet/pull/2202 (https://github.com/dotnet/dotnet/commit/c8c785c5af00422e94edf6818847f63e7a8c499d) and fixes the publishing issue by only publishing the source artifacts from a single VMR build leg (https://github.com/dotnet/dotnet/commit/111862893175a50adcced67c3cb4448760137356). The selected build leg is the one that creates the SB artifacts we publish during a release.
=> Create and publish source tarball and zipball

eng/tools/EmptySdk/Sdk/Sdk.props, eng/tools/EmptySdk/Sdk/Sdk.targets, repo-projects/Directory.Build.props
Partial revert of https://github.com/dotnet/dotnet/commit/ee8b9094a435891d3ee8c40624cb467c51463b9c to unblock the official build
=> Add WindowsDesktop SDK override back until a new SDK is used

eng/common/core-templates/steps/install-microbuild.yml
When the rc1 re-bootstrap happened it reverted to a version of this template that can't be used any longer.
=> [release/10.0.1xx] Restore MB install steps to pre-rebootstrap

eng/pipelines/templates/stages/vmr-validation.yml, test/Microsoft.DotNet.Installer.Tests/LinuxInstallerTests.cs
Fixes: https://github.com/dotnet/dotnet/issues/2290
Netstandard-2.1 dependency was removed from SDK with https://github.com/dotnet/sdk/pull/50354. The change is in VMR's `release/10.0.1xx`, but not yet in `main` due to flow issues. Fixing this in `release/10.0.1xx` first.
Also increasing the timeout for x64 job as there are new tests and we were occasionally hitting the old limit - [example](https://dev.azure.com/dnceng/internal/_build/results?buildId=2785488&view=logs&s=93594280-c135-5b37-42ba-1687921e6d94&j=6e593626-f6df-5699-84b9-2127a964bf7b)
=> [release/10.0.1xx] Remove netstandard-2.1 from installer tests

eng/pipelines/unofficial.yml
Attempting to run the unofficial pipeline causes this error:
```
Encountered error(s) while parsing pipeline YAML:
/eng/pipelines/unofficial.yml (Line: 145, Col: 22): Unexpected parameter 'featureBand'
/eng/pipelines/unofficial.yml: Object reference not set to an instance of an object.
```
This was caused by https://github.com/dotnet/dotnet/pull/2021, which removed the `featureBand` parameter from the `vmr-stages.yml` template but didn't update the `unofficial.yml` pipeline to no longer pass in that parameter.
=> Remove featureBand template parameter

eng/tools/tasks/Microsoft.DotNet.UnifiedBuild.Tasks/SigningValidation.cs
SignCheck is failing in the 10.0 branch due to a missing `"` in [the sdk-task.sh script](https://github.com/dotnet/dotnet/commit/df1de840916a9afea4625beee3a6a2e489255adf#diff-97c1a310b55e5fdb2c17c4bbefb25d537304919618595a1dc93bdf29411f7f3cR13). This issue with the script was fixed in [Fix small typo on sdk-task.sh (#16074) · dotnet/arcade@0646172](https://github.com/dotnet/arcade/commit/0646172696c86219507f3f9cfd28a251ddd86dba), but the change didn't make it into RC1 so it surfaced after we rebootstrapped the VMR the other day.
The fix is to target the sdk-task script in Arcade. Had we been targeting the script in Arcade in the RC1 branch, we would've caught this regression in the script before it was included in the release and introduced by the RC 1 rebootstrap PR.
[Test …
=> Fix SignCheck failing due to bug in sdk-task script

src/arcade/src/Microsoft.DotNet.Build.Tasks.Installers/src/ArEntry.cs, src/arcade/src/Microsoft.DotNet.SignTool.Tests/SignToolTests.cs, src/arcade/src/Microsoft.DotNet.SignTool/src/Configuration.cs, src/arcade/src/Microsoft.DotNet.SignTool/src/ZipData.cs
Fixes https://github.com/dotnet/sdk/issues/50881.
Follow up on https://github.com/dotnet/dotnet/pull/2425.
Related to https://github.com/dotnet/roslyn/issues/80151.
Official build validation run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2797161&view=results
=> Propagate file mode when re-packing through more archive kinds

src/sdk/src/Resolvers/Microsoft.DotNet.MSBuildSdkResolver/MSBuildSdkResolver.cs
There isn't any observable customer impact to this change. This fixes an implementation issue in the previous MSBuild decoupling work that was being hidden by separate MSBuild engine compatibility shims that we added to enable testing the end-to-end of the feature before dev18 was available. If we don't take this change then the net impact is that we aren't able to remove our compat shim in the future and test/rely on the actual designed feature.
If we don't take this for RC2 we wouldn't push for this change, or the compat shim removal, for GA at all. We'd wait until a later feature band/VS release to coordinate that removal more safely.
The SdkResolver is intended to set DOTNET_HOST_PATH to signal to MSBuild Tasks that need a .NET binary/runtime where to look for that binary. Instead it …
=> Make the new SdkResolver set the proper DOTNET_HOST_PATH env var instead of the non-functional DOTNET_HOST env var

repo-projects/aspnetcore.proj
Temporary workaround for dotnet/source-build#5355
Changes aspnetcore to always reference the N-1 version of Roslyn. This ensures it will use 5.0 instead of 5.1 while 5.0 is currently in the N-1 configuration. This will allow the `RequestDelegateGenerator` source generator to be compiled against 5.0 of Roslyn and be compatible with the 5.0 version of the SDK being used in the build.
A more targeted fix will be made later.
=> Reference N-1 version of Roslyn from aspnetcore in SB

test/Microsoft.DotNet.Installer.Tests/LinuxInstallerTests.cs
Fixes: https://github.com/dotnet/sdk/issues/51086
New tests will ensure that we are producing all the expected Linux packages. This will catch any issues early, way before the packages would need to be consumed, i.e. during product release.
=> Add tests for verification of expected set of Linux packages

test/Microsoft.DotNet.Installer.Tests/LinuxInstallerTests.cs
Follow up on https://github.com/dotnet/dotnet/pull/2720
Updates the test based on recent change in packages produced: https://github.com/dotnet/dotnet/pull/2694
=> Azure Linux DEPS packages do not have a newkey variant

src/arcade/src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.props, src/arcade/src/Microsoft.DotNet.SignTool/src/VerifySignatures.cs, src/arcade/src/SignCheck/Microsoft.SignCheck/Utils.cs
`-newkey-` deb files weren't being signed with the correct key.
Also, we didn't import the new public key into our list of valid keys for signing validation. Add the new `microsoft-rolling.asc` file (which contains the new key and will contain all future new keys if the keys change again) so we can validate the new signatures forever (no matter when the keys change).
=> [release/10.0.1xx] Fix certificate selection for debs and fix signing validation for the new key (and all future new keys)
