dotnet/dotnet

packages/archive/archiveArtifacts.txt

Related to https://github.com/dotnet/source-build/issues/3167.
I would like to update this manually to workaround https://github.com/dotnet/source-build/issues/3167 until a long term solution is implemented.  This issue is causing a few prebuilts which I would like to eliminate.

Update archiveArtifacts to correct version

---

src/source-mappings.json

https://github.com/dotnet/arcade/issues/11982

Start synchronizing `source-mappings.json` from `dotnet/installer`

---

README.md

Revert "Update VMR README.md timeframe around two-way code flow"

---

eng/pipelines/templates/jobs/sdk-diff-tests.yml
eng/pipelines/vmr-license-scan.yml

Closes https://github.com/dotnet/source-build/issues/5107

Target dotnet/dotnet repo in SB Diff PRs

---

build.sh

Ports the changes from https://github.com/dotnet/sdk/pull/48720
Fixes https://github.com/dotnet/source-build/issues/4975

Use OfficialBuildId from SB release manifest

---

repo-projects/Directory.Build.props
repo-projects/runtime.proj
src/arcade/Documentation/UnifiedBuild/Unified-Build-Controls.md
src/arcade/eng/common/core-templates/steps/source-build.yml

from https://github.com/dotnet/dotnet/pull/176

Follow-up on feedback from VMR inner/outer removal

---

src/arcade/src/Microsoft.DotNet.Arcade.Sdk/tools/RepoDefaults.props
src/arcade/src/Microsoft.DotNet.Arcade.Sdk/tools/Tools.proj

Forgot two hits in https://github.com/dotnet/dotnet/pull/423. I shouldn't trust dev.vscode's search

Fix a few missing PrebuiltUsage properties

---

eng/pipelines/vmr-compare.yml

Closes https://github.com/dotnet/source-build/issues/5151

Trigger comparison pipeline after publishing the assets

---

build.sh

Usage diff: https://github.com/am11/dotnet-riscv/commit/38e376ecca60a7802a7e2efa4bfb39687f1345ba
Build: https://github.com/am11/dotnet-riscv/actions/runs/15049596169

Call prep if cache dir doesn't exist

---

eng/pipelines/templates/stages/source-build-and-validate.yml

Fixes https://github.com/dotnet/source-build/issues/5198
[Test pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2710840&view=results)

Download NewBinaries.txt in VMR SB validation

---

src/sdk/src/Layout/redist/targets/GenerateBundledVersions.targets

Fixes issues in https://dev.azure.com/dnceng/internal/_git/dotnet-optimization/pullrequest/50255

Enable bundled version props files in the PGO builds

---

eng/pipelines/source-build-sdk-diff-tests.yml

Closes https://github.com/dotnet/source-build/issues/5220

Add dotnet-source-build-pre10.0 as a pipeline trigger

---

prep-source-build.sh

Closes https://github.com/dotnet/source-build/issues/5228

Fix artifacts-rid arg

---

eng/pipelines/ci.yml

Fixes https://github.com/dotnet/dotnet/issues/1118

Add signed main build on weekends

---

eng/Publishing.props

Copy SDK tarball to the artifacts/assets root for SB compatibility

---

eng/update-band.ps1
eng/update-band.sh

Related to https://github.com/dotnet/dotnet/issues/1106
This PR introduces two scripts, bash and pwsh, for keeping the `10.0.2xx-dev` branch updated with new changes from main branch, excluding any changes that were made in deleted repos.

Scripts to keep 10.0.2xx branch up-to-date with main

---

eng/pipelines/templates/steps/vmr-validate-signing.yml

Fixes validation issues in some legs. We were picking up the SB artifacts

Only download specific sets of artifacts

---

src/msbuild/eng/Version.Details.xml
src/msbuild/eng/Versions.props
src/msbuild/eng/common/core-templates/job/job.yml
src/msbuild/eng/common/core-templates/jobs/jobs.yml
src/msbuild/eng/common/core-templates/jobs/source-build.yml
src/msbuild/eng/common/core-templates/steps/install-microbuild.yml
src/msbuild/global.json
src/msbuild/src/Tasks/Microsoft.Common.CurrentVersion.targets
src/source-manifest.json

Revert "[release/10.0.1xx-preview7] Source code updates from dotnet/msbuild"

---

eng/tools/BinaryToolKit/DetectBinaries.cs

Closes https://github.com/dotnet/source-build/issues/5241
Previously, the `IsBinaryAsync` function was executed on every file, including those that should have been excluded from binary detection. This led to file access errors such as:
```
/__w/1/s/eng/init-detect-binaries.proj(22,5): error : The process cannot access the file '/__w/1/s/prereqs/packages/previously-source-built/Microsoft.CodeAnalysis.VisualBasic.Workspaces.5.0.0-1.25302.104.nupkg' because it is being used by another process.
```
These errors occurred when poison detection and binary scan processes attempted to access the same files in parallel.
This PR fixes those errors by updating the binary detection logic so that `IsBinaryAsync` is only called on files that are not excluded by the allowed binaries list. As a result, …

Don't check if an excluded file is a binary

---

eng/PublishSourceBuild.props
eng/VmrLayout.props
eng/init-poison.proj
eng/tools/tasks/Microsoft.DotNet.SourceBuild.Tasks.LeakDetection/CheckForPoison.cs
test/Microsoft.DotNet.SourceBuild.Tests/assets/PoisonTests/PoisonUsage.txt

Fixes https://github.com/dotnet/source-build/issues/5297
[Test pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2766280&view=results)

Check source-built packages for poison

---

.github/policies/assign_ownership.yml

Initial attempt at automatically adding reviewers per directory.

Auto-add reviewers

---

src/aspnetcore/global.json

[Dependency flow PR](https://github.com/dotnet/aspnetcore/pull/63109) keeps being annoying and reverting the SDK update, so just forcing it here.

Update SDK in aspnetcore

---

eng/pipelines/templates/jobs/vmr-build.yml

Fixes https://github.com/dotnet/source-build/issues/5311
test build - https://dev.azure.com/dnceng/internal/_build/results?buildId=2772916

Disable libunwind usage with useSystemLibraries in CI

---

eng/Version.Details.props
eng/Version.Details.xml
eng/Versions.props
eng/common/core-templates/steps/install-microbuild.yml
global.json
src/arcade/Directory.Build.targets
src/arcade/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.targets

Forward-port of https://github.com/dotnet/dotnet/pull/2037

[main] Re-Bootstrap Source Build to .NET 10.0.100-rc.1.25420.111

---

eng/Version.Details.props
eng/Version.Details.xml
eng/Versions.props
eng/common/core-templates/steps/install-microbuild.yml
global.json
src/arcade/Directory.Build.targets
src/arcade/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.targets

Forward-port of https://github.com/dotnet/dotnet/pull/2037

[release/10.0.1xx] Re-Bootstrap Source Build to .NET 10.0.100-rc.1.25420.111

---

src/sdk/src/Layout/redist/redist.csproj

Change Introduced: https://github.com/dotnet/dotnet/commit/b8571bf9f3763a3c496e7af8465c624ff62b44c0#diff-39156b4002161dcafe840ba7a714dbd975678a91cfc2394538a69c64b25d59d9R32
Change Reverted: https://github.com/dotnet/dotnet/commit/8d1299b5d827c40ed550060448d104946d436681#diff-39156b4002161dcafe840ba7a714dbd975678a91cfc2394538a69c64b25d59d9L32

Reapply NuGet.Localization redist change lost in flow

---

eng/pipelines/templates/stages/source-build-stages.yml

Removing these now to unblock official builds.
Related to https://github.com/dotnet/dotnet/issues/2017
Contributes to https://github.com/dotnet/source-build/issues/5330

Remove Mono SB legs

---

eng/pipelines/templates/jobs/vmr-build.yml
prep-source-build.sh

Revert "Retry on all errors for PSB download"

---

eng/download-source-built-archive.sh
eng/pipelines/templates/jobs/vmr-build.yml
eng/pipelines/templates/stages/source-build-and-validate.yml
prep-source-build.sh

Backport of https://github.com/dotnet/dotnet/pull/2403
Fixes https://github.com/dotnet/source-build/issues/5332

Download shared components outside of prep script

---

eng/pipelines/templates/stages/source-build-stages.yml

Fixes dotnet/source-build#5341

Skip tests for Mono that require MS artifacts

---

src/runtime/src/mono/nuget/Directory.Build.targets

Work in progress PR. Fixes for 10.0.0 stable build from servicing exercise.

[release/10.0.1xx] 10.0.0 Servicing exercise fix rollup

---

src/roslyn/src/Compilers/Core/MSBuildTask/ManagedToolTask.cs
src/roslyn/src/Compilers/Shared/BuildServerConnection.cs

Reapplying https://github.com/dotnet/dotnet/pull/2585 which seems to have been reverted in https://github.com/dotnet/dotnet/pull/2613.

[.NET10 RC2] Unset other DOTNET_ROOT env vars when launching apphosts

---

src/razor/azure-pipelines-official.yml
src/razor/eng/Versions.props
src/razor/eng/config/PublishData.json
src/razor/src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/SourceGenerators/RazorCohostingOptions.cs
src/razor/src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
src/razor/src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/HtmlDocumentPublisher.cs
src/razor/src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/SemanticTokensRefreshNotifier.cs
src/razor/src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Options/OptionsStorage.cs
src/razor/src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Options/SettingsNames.cs
src/razor/src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
src/source-manifest.json

Resetting razor to `909624c615247ce1bc4b81cd76c67f0011ce018e`
https://github.com/dotnet/arcade-services/issues/5310

[release/10.0.1xx] Reset razor to unblock flow

---

src/razor/azure-pipelines-official.yml
src/razor/eng/Versions.props
src/razor/eng/config/PublishData.json
src/razor/src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/SourceGenerators/RazorCohostingOptions.cs
src/razor/src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
src/razor/src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/HtmlDocumentPublisher.cs
src/razor/src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/SemanticTokensRefreshNotifier.cs
src/razor/src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Options/OptionsStorage.cs
src/razor/src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Options/SettingsNames.cs
src/razor/src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
src/source-manifest.json

Resetting razor to `909624c615247ce1bc4b81cd76c67f0011ce018e`
https://github.com/dotnet/arcade-services/issues/5310

[release/10.0.1xx-rc2] Reset razor to unblock flow

---

docs/Repository-Onboarding.md

This document provides a step-by-step guide for onboarding new repositories into the VMR (Virtual Monolithic Repository). It covers:
- Prerequisites and repository requirements
- 6-step onboarding process from source mappings to validation
- Proper references to existing detailed VMR documentation
- Guidance on handling license and binary validation
- Getting help resources
The guide follows a one-sentence-per-line convention and focuses on practical, actionable steps rather than duplicating existing detailed documentation.

Add VMR Repository Onboarding Guide
